vname: Sync to GitLab

on:
  push:
    branches:
      - main  # or whichever branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the full history to avoid shallow clone issues

    - name: Set up Git
      run: |
        git config user.name "dragon731012"
        git config user.email "dragon73101@gmail.com"

    - name: Add or update GitLab remote
      run: |
        git remote set-url gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/potato12341/codeserver.git || git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/potato12341/codeserver.git
        git fetch gitlab

    - name: Force push to GitLab main
      run: |
        git push gitlab main --force  # Force push local main to GitLab main branch
